---
- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install required packages
  ansible.builtin.apt:
    name:
      - nginx
      - unzip
      - curl
    state: present

- name: Create application directory
  ansible.builtin.file:
    path: /var/www/restaurant-web-app
    state: directory
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: "0755"

- name: Create releases directory
  ansible.builtin.file:
    path: /var/www/restaurant-web-app/releases
    state: directory
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: "0755"

- name: Create shared directory
  ansible.builtin.file:
    path: /var/www/restaurant-web-app/shared
    state: directory
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: "0755"