name: Production Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    uses: ./.github/workflows/shared-build.yml

  security:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Secret Scan
        uses: trufflesecurity/trufflehog@main

  # deploy:
  #   needs:
  #     - build
  #     - security

  #   uses: ./.github/workflows/shared-deploy.yml

  #   with:
  #     inventory: production.ini
  #     environment: production

  #   secrets:
  #     SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_KEY }}