name: Production Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    uses: ./.github/workflows/shared-build.yml
  deploy:
    needs: build
    uses: ./.github/workflows/shared-deploy.yml

    with:
      inventory: production.ini
      environment: production
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.DEV_SSH_KEY }}
      SSH_PASSPHRASE: ${{ secrets.DEV_SSH_PASSPHRASE }}
      DEV_HOST: ${{ secrets.PROD_HOST }}