name: Staging Pipeline

on:
  push:
    branches:
      - "release/**"

jobs:

  build:
    uses: ./.github/workflows/shared-build.yml

  deploy:
    needs: build

    uses: ./.github/workflows/shared-deploy.yml

    with:
      inventory: staging.ini
      environment: staging

    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.STAGE_SSH_KEY }}