name: Shared Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      artifact-name: restaurant-web-app-build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.1
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Build Application
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: restaurant-web-app-build
          path: dist/