name: Shared Build

on:
  workflow_call:

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.1
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint


  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.1
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test


  build:
    name: Build Application
    runs-on: ubuntu-latest

    needs:
      - lint
      - test

    outputs:
      artifact-name: restaurant-web-app-build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.1
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: restaurant-web-app-build
          path: dist/