name: Shared Deploy

on:
  workflow_call:
    inputs:
      inventory:
        required: true
        type: string

      environment:
        required: true
        type: string

    secrets:
      SSH_PRIVATE_KEY:
        required: true

      SSH_PASSPHRASE:
        required: true

      DEV_HOST:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: restaurant-web-app-build
          path: dist

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
      
      - name: Configure SSH
        shell: bash
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          printf '%s\n' '${{ secrets.SSH_PRIVATE_KEY }}' \
          > ~/.ssh/ec2_rsa_key

          chmod 600 ~/.ssh/ec2_rsa_key
      
      - name: Configure SSH
        shell: bash
        env:
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        run: |
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh

            printf '%s\n' '${{ secrets.SSH_PRIVATE_KEY }}' \
              > ~/.ssh/ec2_rsa_key

            chmod 600 ~/.ssh/ec2_rsa_key

            cat > ~/.ssh/askpass.sh <<'EOF'
            #!/bin/bash
            printf '%s\n' "$SSH_PASSPHRASE"
            EOF

            chmod 700 ~/.ssh/askpass.sh

            eval "$(ssh-agent -s)"

            export SSH_ASKPASS="$HOME/.ssh/askpass.sh"
            export SSH_ASKPASS_REQUIRE=force
            export DISPLAY=:0

            setsid ssh-add ~/.ssh/ec2_rsa_key < /dev/null

            echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> "$GITHUB_ENV"
            echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> "$GITHUB_ENV"



      - name: Verify SSH
        env:
          DEV_HOST: ${{ secrets.DEV_HOST }}
        run: |
          ssh \
          -o StrictHostKeyChecking=no \
          ubuntu@"$DEV_HOST" \
          "echo SSH connection successful"



      - name: Deploy with Ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook \
            -i ansible/inventory/${{ inputs.inventory }} \
            ansible/playbooks/deploy.yml \
            -e "artifact_path=${GITHUB_WORKSPACE}/dist" \
            -e "release_id=$(date +%Y%m%d%H%M%S)"